### ISSUE TITLE
Error on status command

### ISSUE THREAD

**Issue by Johnnyreyman** [kmille/riseup-vpn-configurator#5]
When running the command ~/.local/bin/riseup-vpn-configurator --status I keep running into an error:
ERROR: Could not find user/group: "getpwnam(): name not found: 'openvpn'"
[![asciicast](https://asciinema.org/a/7f8CVqJNjBdCmaQueunf6HyaN.svg)](https://asciinema.org/a/7f8CVqJNjBdCmaQueunf6HyaN)

**Comment by kmille** [comment]
A) What system do you use?
B) Do you have installed the `openvpn` package (or openvpn-client?)?
In this case the user `openvpn` does not exist.

**Comment by Johnnyreyman** [comment]
I am using Ubuntu 22.04 LTS with the `openvpn` package. I have tried creating the user/group and the script still does not recognize its existence.

**Comment by kmille** [comment]
BTW: I haven't checked it, but you have entered a password and probably captured it with asciinema!

Can you please show me your output?
```bash
kmille@linbox:~ groups openvpn
openvpn
kmille@linbox:~ id openvpn
uid=965(openvpn) gid=965(openvpn) groups=965(openvpn)
```

**Comment by kmille** [comment]
I fixed the issue. You can now specify user/group in the config file. You can use -t to get  a new "config file template". Please try and give feedback.

**Comment by rojenzaman** [comment]
Notice that the openvpn user and group name in Ubuntu is `nm-openvpn`.

My config:

```conf
---
# /etc/riseup-vpn.yaml

server: vpn07-par.riseup.net
protocol: udp
port: 53

# excluded_routes: list servcies that should not be routed over VPN
# can be an ipaddress, network or hostname
# your local subnet is excluded by default
excluded_routes:
  - 8.8.8.8
  - 192.168.123.0/24
  - us02web.zoom.us

# os user/group
user: nm-openvpn
group: nm-openvpn

```


Please run before start:

```bash
riseup-vpn-configurator --update
riseup-vpn-configurator --generate-config

```
